config/routes.rb
Grammable::Application.routes.draw do
  devise_for :users
  root "grams#index"
  resources :grams do
    resources :comments, only: :create
  end
end

app/models/gram.rb
class Gram < ApplicationRecord
  validates :message, presence: true
  validates :picture, presence: true
  has_many :comments

  mount_uploader :picture, PictureUploader

  belongs_to :user
end

app/controllers/grams_controller.rb
class GramsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  def update
    @gram = Gram.find_by_id(params[:id])
     return render_not_found if @gram.blank?
       if @gram.user != current_user
    return render plain: 'Forbidden :(', status: :forbidden
  end


    @gram.update_attributes(gram_params)

     if @gram.valid?
    redirect_to root_path
  else
    return render :edit, status: :unprocessable_entity
  end
   
  end

  def new
    @gram = Gram.new
  end

  def index
    @grams = Gram.all
  end

  def show
    @gram = Gram.find_by_id(params[:id])
    return render_not_found if @gram.blank?
  end

  def edit
    @gram = Gram.find_by_id(params[:id])
    return render_not_found if @gram.blank?
     if @gram.user != current_user
    render plain: 'Forbidden :(', status: :forbidden
  end
  end

  def create
    @gram = current_user.grams.create(gram_params)
    if @gram.valid?
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def gram_params
    params.require(:gram).permit(:message)
  end

  def render_not_found
     render plain: "#{status.to_s.titleize} :(", status: status
  
  end
  
  def destroy
  @gram = Gram.find_by_id(params[:id])
  return render_not_found if @gram.blank?
  if @gram.user != current_user
    return render plain: 'Forbidden :(', status: :forbidden
  end
  @gram.destroy
  redirect_to root_path
end
end

app/helpers/grams_helper.rb
module GramsHelper
end

app/views/grams/edit.html.erb
<div class="col-10 offset-1 col-sm-8 offset-sm-2 col-md-6 offset-md-3 card form">
  <h2>Edit Gram</h2>


<%= simple_form_for @gram do |f| %>
  <%= f.input :message %>
  <%= f.input :picture %>
  <%= f.submit 'Update', class: 'my-btn' %>
  <%= f.submit %>
<% end %>

</div>

app/views/grams/index.html.erb
<h1>Grams!</h1>
<div class="col-10 offset-1 col-sm-8 offset-sm-2 col-md-6 offset-md-3">
  <% @grams.each do |gram| %>
  <div class="card">
    <div class="handle"><%= gram.user.email %></div>
    <%= image_tag gram.picture, class: 'img-fluid' %>
    <p>
      <%= gram.message %>
    </p>

     <div class="gram-actions float-right">
      <% if current_user && current_user == gram.user %>
        <%= link_to 'Edit', edit_gram_path(gram) %>
        <%= link_to 'Destroy', gram_path(gram), method: :delete, data: {confirm: 'Are you sure?'} %>
      <% end %>
    </div>
    <br class="clear-fix" />
      <div class="comments">
      <h3>Comments</h3>
       <% gram.comments.each do |comment| %>
          <div class="comment">
            <span class="comment_handle">
              <%= comment.user.email %>
            </span>

            <%= comment.message %>
          </div>
        <% end %>

      <h4>Add a comment</h4>
      <%= simple_form_for Comment.new, url: gram_comments_path(gram) do |f| %>
        <%= f.input :message %>
        <%= f.submit 'Add Comment', class: 'my-btn' %>
      <% end %>
    </div>
  </div>
  <% end %>
</div>

app/views/grams/new.html.erb
<h1>New Gram</h1>

<%= simple_form_for @gram do |f| %>
  <%= f.input :message %>
  <%= f.submit "Post!" %>
<% end %>